steps:
  # install dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  # build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  # deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['--project', 'github-actions-256012', 'app', 'deploy', '--quiet']
